title: Andrew Payne
logo: /assets/img/IMG_3871.HEIC
description: University Innovator and Design Thinker. I am passionate about using design thinking to create a positive change in higher education to engage students in project-based and experiential learning opportunities. Experienced in software engineering, and electronics and controls. 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
