title: Andrew Payne
logo: images/IMG_6279-1.jpeg
description: I am a Software Test Engineer at WillowTree working on mobile applications for a Fortune 500 client. My current focus includes Native iOS and Android automation testing, automation investigation and reporting, manual testing, test case design, and defect reporting.
show_downloads: false
google_analytics: UA-144819847-1
theme: jekyll-theme-minimal

