title: Andrew Payne
logo: raytheon_intern_headshot.jpg
description: University Innovator and Design Thinker. I am passionate about using design thinking to create a positive change in higher education to engage students in project-based and experiential learning opportunities. Experienced in software engineering, and electronics and controls. 
show_downloads: false
google_analytics: UA-144819847-1
theme: jekyll-theme-minimal

