title: Andrew Payne
logo: images/germany.jpg
description: Engineer, University Innovator, Design Thinker. I'm a Senior at James Madison University and I am passionate about using design thinking + emerging technologies to create a positive change on the world around me. As an engineer well versed in multiple disciplines, I have work experience in the Software Engineering Industry, project experience in Electrical Engineering, and the ability to adapt to fast paced, challenging environment.
show_downloads: false
google_analytics: UA-144819847-1
theme: jekyll-theme-minimal

